##
# This is an EXAMPLE secrets file that's included so that espHome will build the project
# EIther supply your own secrets file or change the values below to be appropriate!
##
# Wifi Credentials
wifi_ws3_ssid: myWiFiNetwork
wifi_ws3_pass: myWifiPassword

# MQTT credentials
mqtt_host: 192.168.1.2
mqtt_user: mosquitto
mqtt_pass: letmein

# OTA
ota_pass: anyBodyWithThisPassWordCanUploadNewFirmware
