##
# A simple bridge between a cheap chinese WS3 weather station and MQTT.
# Powered by ESPHome and intended for HomeAssistant integration (via MQTT)
#
# The heavy lifting is done in the ws3.h file
# This YAML file configures ESPHome to use the outputs from ws3.h
#
# Karl Quinsland, 2019.
# Free to use for any non-commercial purposes.
# Commercial use requires express written consent from me.
##
# Change the values here, or the lookup key in your secrets.yaml file
# See: https://esphome.io/guides/faq.html#how-do-i-use-my-home-assistant-secrets-yaml
substitutions:
  # WIFI
  wifi_name: !secret wifi_ws3_ssid
  wifi_pass: !secret wifi_ws3_pass

  # MQTT
  mqtt_host: !secret mqtt_host
  mqtt_user: !secret mqtt_user
  mqtt_pass: !secret mqtt_pass

  # OTA/Updates
  ota_pass: !secret ota_pass

  # Displayed in HA frontend
  friendly_name: "WS3 Bridge"
  friendly_short: "WS3"

esphome:
  name: ws3
  platform: ESP32
  # WeMos does not make a esp32 module in the d1 MINI form factor but that's
  # what i have. It's a d1 mini pin compatible kit from china. ~$6/board makes it
  # a wonderfully cheap/powerful board for most ESPHome devices
  #
  # See: https://www.aliexpress.com/item/MH-ET-LIVE-ESP32-MINI-KIT-WiFi-Bluetooth-Internet-of-Things-development-board-based-ESP8266-Fully/32819107932.html
  ##
  # See: https://docs.platformio.org/en/latest/boards/espressif32/esp32doit-devkit-v1.html
  board: mhetesp32minikit
  # Components required for integration into the ESPHome framework
  # See: https://esphome.io/custom/custom_component.html
  includes:
    - ws3.h

# See: https://esphome.io/components/wifi.html
wifi:
  ssid: ${wifi_name}
  password: ${wifi_pass}

# Enable logging
logger:

# Enable status LED; very low resolution logging :)
# See: https://esphome.io/components/status_led.html
status_led:
  # Wemos uses GPIO2 for the built in LED
  pin:
    number: GPIO2
    # It does not need an inversion (active low)
    inverted: false

ota:
  # See: https://esphome.io/components/ota.html
  password: ${ota_pass}

# See: https://esphome.io/components/mqtt.html
mqtt:
  broker: ${mqtt_host}
  username: ${mqtt_user}
  password: ${mqtt_pass}

# See: https://esphome.io/components/web_server.html
# Simple debug log + states + FW upload
web_server:
  port: 80

uart:
  # The ESP32 has 3 UARTS; UART2 is ideal for supporting the WS3
  # UART2: GPIO17 is espRX and GPIO16 is espTX
  id: uart_bus
  tx_pin: GPIO16
  rx_pin: GPIO17
  # The WS3 supports either 2400 or 9600 baud. Default config is 2400 baud.
  baud_rate: 2400

binary_sensor:
  # A "connected?" status sensor that - as long as sensor + mqtt + HA are working -
  #   will always display "true". Allows for easy detection of sensor failure from HA
  # See: https://esphome.io/components/binary_sensor/status.html
  - platform: status
    name: "${friendly_name} Status"

sensor:
  # A measurement that is useful for detecting wifi reception problems
  # Make sure to set HA to retain this data for a very short time!
  #
  # See: https://community.home-assistant.io/t/iron-gate-sensor/97656/6
  - platform: wifi_signal
    name: "${friendly_name} Wifi Signal"
    update_interval: 5s
    filters:
      - sliding_window_moving_average:
          # hold 15 measurements, taken every 5 seconds
          window_size: 15
          # every 15 seconds, send the updated result..
          send_every: 15

  # See: https://esphome.io/custom/custom_component.html
  - platform: custom
    lambda: |-
      auto ws3 = new WS3(id(uart_bus));
      App.register_component(ws3);
      return {
        ws3->temperature_sensor, 
        ws3->pressure_sensor, 
        ws3->humidity_sensor, 
        ws3->wind_speed_current_sensor,
        ws3->wind_speed_peak_5m_sensor,
        ws3->wind_direction_sensor,
        ws3->rain_fall_1h_sensor, 
        ws3->rain_fall_24h_sensor,

        // Comment out the fields named `particles_` if not using the PM2.5 sensor
        ws3->particles_03um,
        ws3->particles_05um,
        ws3->particles_10um,
        ws3->particles_25um,
        ws3->particles_50um,
        ws3->particles_100um,
        
      };

    sensors:
      - name: "${friendly_short} Temperature"
        unit_of_measurement: °F
        accuracy_decimals: 2
        # Mark the value as 'none/unknown' after 5min
        expire_after: 5min
      - name: "${friendly_short} Air Pressure"
        unit_of_measurement: hPa
        accuracy_decimals: 2
        expire_after: 5min
      - name: "${friendly_short} Relative Humidity"
        unit_of_measurement: "%"
        accuracy_decimals: 2
        expire_after: 5min
      - name: "${friendly_short} Wind Speed"
        unit_of_measurement: mph
        accuracy_decimals: 2
        expire_after: 5min
      - name: "${friendly_short} Wind Speed (Peak; 5min)"
        unit_of_measurement: mph
        accuracy_decimals: 2
        expire_after: 5min
      - name: "${friendly_short} Wind Direction Sensor"
        unit_of_measurement: °
        accuracy_decimals: 1
        expire_after: 5min
      - name: "${friendly_short} Rainfall (Sum; 1hr)"
        unit_of_measurement: inches
        accuracy_decimals: 2
        expire_after: 5min
      - name: "${friendly_short} Rainfall (Sum; 24hr)"
        unit_of_measurement: inches
        accuracy_decimals: 2
        expire_after: 5min
      ##
      # PM 2.5
      # Note: HomeAssistant will display the values as a series of colored blocks rather than a graph if there's no units indicated
      # However, we can default to 0 accuracy_decimals as the value we're returning is an int
      ##
      - name: "${friendly_short} Air Particles > 0.3μm"
        expire_after: 5min
        unit_of_measurement: particles
      - name: "${friendly_short} Air Particles > 0.5μm"
        expire_after: 5min
        unit_of_measurement: particles / .1L
      # As in, the count of Particles > 1.0um / 0.1L air
      - name: "${friendly_short} Air Particles > 1.0μm"
        expire_after: 5min
        unit_of_measurement: particles
      - name: "${friendly_short} Air Particles > 2.5μm"
        expire_after: 5min
        unit_of_measurement: particles
      - name: "${friendly_short} Air Particles > 5.0μm"
        expire_after: 5min
        unit_of_measurement: particles
      - name: "${friendly_short} Air Particles > 10.0μm"
        expire_after: 5min
        unit_of_measurement: particles
